language: python

cache: pip

services:
    - redis-server

addons:
    apt:
         packages:
             - libpq5

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

install:
    - python setup.py install

script:
    - misp-modules.py &
    - sleep 15
    - python setup.py test
    - pkill misp-modules.py
