language: python

services:
    - redis-server

cache: pip

python:
    - "3.5"
    - "3.5-dev"
    - "3.6"
    - "3.6-dev"
    - "3.7"
    - "3.7-dev"

install:
    - pip install -U nose codecov pytest
    - pip install -U -r REQUIREMENTS
    - pip install .

script:
    - coverage run -m --parallel-mode --source=misp_modules misp_modules.__init__  -l 127.0.0.1 &
    - pid=$!
    - sleep 5
    - nosetests --with-coverage --cover-package=misp_modules
    - kill -s INT $pid
    - pushd ~/
    - coverage run -m --parallel-mode --source=misp_modules misp_modules.__init__ -s -l 127.0.0.1 &
    - pid=$!
    - popd
    - sleep 5
    - nosetests --with-coverage --cover-package=misp_modules
    - kill -s INT $pid

after_success:
    - coverage combine .coverage*
    - codecov
