language: python

cache: pip

services:
    - redis-server

addons:
    apt:
         packages:
             - libpq5

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

install:
    - pip install -r REQUIREMENTS

script:
    - pushd bin
    - ./misp-modules.py -t
    - popd
