language: python

services:
    - redis-server

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "nightly"

install:
    - pip install -U nose
    - pip install coveralls
    - pip install codecov
    - pip install -U -r REQUIREMENTS
    - pip install .
    # Force travis to use the right pymisp
    - git clone https://github.com/MISP/PyMISP.git
    - cd PyMISP 
    - python setup.py install
    - cd ..
script:
    - coverage run -m --parallel-mode --source=misp_modules misp_modules.__init__ &
    - pid=$!
    - sleep 5
    - nosetests --with-coverage --cover-package=misp_modules
    - kill -s INT $pid
    - pushd ~/
    - coverage run -m --parallel-mode --source=misp_modules misp_modules.__init__ -s &
    - pid=$!
    - popd
    - sleep 5
    - nosetests --with-coverage --cover-package=misp_modules
    - kill -s INT $pid

after_success:
    - coverage combine .coverage*
    - codecov
    - coveralls
