language: python

services:
    - redis-server

cache: pip

python:
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"

install:
    - sudo apt-get install libzbar0 libzbar-dev libpoppler-cpp-dev
    - pip install pipenv
    - pipenv install --dev
    # MKDOCS
    - pip install -r docs/REQUIREMENTS.txt

script:
    - pipenv run coverage run -m --parallel-mode --source=misp_modules misp_modules.__init__  -l 127.0.0.1 &
    - pid=$!
    - sleep 5
    - pipenv run nosetests --with-coverage --cover-package=misp_modules
    - kill -s KILL $pid
    - pushd ~/
    - pipenv run coverage run -m --parallel-mode --source=misp_modules misp_modules.__init__ -s -l 127.0.0.1 &
    - pid=$!
    - popd
    - sleep 5
    - pipenv run nosetests --with-coverage --cover-package=misp_modules
    - kill -s KILL $pid
    - pipenv run flake8 --ignore=E501,W503 misp_modules

after_success:
    - pipenv run coverage combine .coverage*
    - pipenv run codecov
    # MKDOCS
    - make ci_generate_docs

deploy:
  provider: pages
  local-dir: site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master