name: Release Python package and docs pages

on:

  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packages
        run: sudo apt-get install libpoppler-cpp-dev libzbar0 tesseract-ocr yara

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: poetry install --with docs

      - name: Build package
        run: poetry build

      - name: Build documentation
        run: make generate_docs

      - name: Setup pages
        uses: actions/configure-pages@v3

      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

      - name: Upload package artifcat
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/


#   publish-to-pypi:
#     runs-on: ubuntu-latest
#     needs: build
# 
#     steps:
#       - name: Download dist files
#         uses: actions/download-artifact@v3
#         with:
#           name: python-package-distributions
#           path: dist/
# 
#       - name: Publish to PyPI
#         uses: pypa/gh-action-pypi-publish@release/v1
#         # with:
#         #   repository-url: https://test.pypi.org/legacy/
# 
# 
#   deploy-gh-pages:
#     runs-on: ubuntu-latest
#     needs: build
# 
#     permissions:
#       pages: write
#       id-token: write
# 
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
# 
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v2
